[project]
name = "jupyter-gpu-dev"
version = "0.1.0"
description = "Jupyter Labs in container for cloud usage"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars",
    "numpy",
    "jupyter",
    "ipykernel",
]

